;;;; .emacs --- init file for editing git commit messages

;; Copyright (C) Zalan Kemenczy

;; Author:  Zalan Kemenczy <zalan.k@gmail.com>
;; Created: Feb 12, 2007
;; Revised: Mar 2, 2015
;; Emacs v: 24.4.90.1


(add-to-list 'load-path "~/local/share/elisp/")
(add-to-list 'load-path "~/.emacs.conf/")

;; Load most packages except magit.
(setq package-load-list '((magit nil) all))
(package-initialize)

(setq no-helm-rebind-prefix t)

;; Configure smartparens
(load "smartparens-init.el")
(load "global-keybindings.el")
(load "ui-display.el") 
(load "theme.el")
 
;; Overrides
(setq kill-emacs-query-functions nil)
(setq my-frame-alist `((width . 90) (height . 30)))

(setq default-frame-alist (append my-frame-alist default-frame-alist))
(setq initial-frame-alist (append my-frame-alist initial-frame-alist))

;;;; Customize
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#c0c0c0" :foreground "#303030" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 130 :width normal :foundry "nil" :family "Fira Mono"))))
 '(border ((t (:background "#a9a9a9"))))
 '(cider-debug-code-overlay-face ((t (:inherit highlight))))
 '(cider-fringe-good-face ((t (:inherit highlight))))
 '(cider-result-overlay-face ((t (:inherit highlight))))
 '(company-scrollbar-bg ((t nil)))
 '(company-scrollbar-fg ((t (:inherit highlight))))
 '(company-tooltip ((t (:inherit region))))
 '(company-tooltip-annotation ((t (:inherit font-lock-comment-face))))
 '(company-tooltip-common ((t (:inherit font-lock-type-face))))
 '(company-tooltip-search ((t (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((t (:inherit highlight))))
 '(cursor ((t (:background "HotPink3" :foreground "#303030"))))
 '(ecb-default-highlight-face ((t (:inherit highlight))))
 '(ecb-mode-line-prefix-face ((t (:inherit font-lock-builtin-face))))
 '(ecb-tag-header-face ((t (:inherit highlight))))
 '(error ((t (:inherit font-lock-type-face :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "gray30"))))
 '(font-lock-comment-face ((t (:foreground "gray41" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#717a96"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face ((t (:foreground "#246db0"))))
 '(font-lock-keyword-face ((t (:foreground "grey30" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#817595"))))
 '(font-lock-type-face ((t (:foreground "PaleVioletRed4"))))
 '(font-lock-variable-name-face ((t (:foreground "#486b7a"))))
 '(fringe ((t (:background "#c0c0c0" :foreground "#777777"))))
 '(header-line ((t (:inherit mode-line :background "#b0b0b0" :foreground "#555555" :box nil))))
 '(helm-M-x-key ((t (:inherit link :underline t))))
 '(helm-buffer-directory ((t (:inherit font-lock-function-name-face))))
 '(helm-buffer-not-saved ((t (:inherit font-lock-type-face))))
 '(helm-buffer-process ((t (:inherit font-lock-comment-face))))
 '(helm-buffer-saved-out ((t (:inherit font-lock-variable-name-face))))
 '(helm-candidate-number ((t (:inherit org-mode-line-clock))))
 '(helm-etags-file ((t (:inherit font-lock-string-face))))
 '(helm-ff-directory ((t (:inherit font-lock-function-name-face))))
 '(helm-ff-dotted-directory ((t (:inherit font-lock-builtin-face))))
 '(helm-ff-dotted-symlink-directory ((t (:inherit (font-lock-constant-face highlight)))))
 '(helm-ff-executable ((t (:inherit font-lock-function-name-face))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-invalid-symlink ((t (:inherit (font-lock-type-face highlight)))))
 '(helm-ff-prefix ((t (:inherit font-lock-keyword-face))))
 '(helm-ff-symlink ((t (:inherit font-lock-constant-face))))
 '(helm-grep-file ((t (:inherit font-lock-builtin-face))))
 '(helm-grep-finish ((t (:inherit font-lock-variable-name-face))))
 '(helm-grep-lineno ((t (:inherit font-lock-comment-face))))
 '(helm-grep-match ((t (:inherit link :underline nil :weight bold))))
 '(helm-grep-running ((t (:inherit font-lock-type-face))))
 '(helm-header ((t (:inherit header-line :slant italic))))
 '(helm-history-remote ((t (:inherit font-lock-string-face))))
 '(helm-lisp-completion-info ((t (:inherit font-lock-type-face))))
 '(helm-lisp-show-completion ((t (:inherit font-lock-variable-name-face))))
 '(helm-match ((t (:inherit ido-only-match))))
 '(helm-match-item ((t (:inherit lazy-highlight))))
 '(helm-moccur-buffer ((t (:inherit font-lock-builtin-face))))
 '(helm-prefarg ((t (:inherit font-lock-builtin-face))))
 '(helm-selection ((t (:inherit highlight))))
 '(helm-separator ((t (:inherit font-lock-type-face))))
 '(helm-source-header ((t (:inherit font-lock-keyword-face :weight bold))))
 '(helm-swoop-line-number-face ((t (:inherit font-lock-comment-face))))
 '(helm-swoop-target-line-block-face ((t (:inherit region))))
 '(helm-swoop-target-line-face ((t (:inherit highlight))))
 '(helm-swoop-target-word-face ((t (:inherit lazy-highlight))))
 '(helm-visible-mark ((t (:inherit region))))
 '(highlight ((t (:background "gray65"))))
 '(ido-indicator ((t (:inherit link :underline nil :width condensed))))
 '(ido-only-match ((t (:inherit font-lock-variable-name-face))))
 '(ido-subdir ((t (:inherit font-lock-function-name-face))))
 '(info-header-xref ((t (:inherit info-xref))))
 '(info-node ((t (:inherit link :slant italic :weight bold))))
 '(isearch ((t (:background "hotpink4" :foreground "#b9b9b9"))))
 '(isearch-fail ((t (:inherit isearch))))
 '(ivy-current-match ((t (:inherit highlight))))
 '(ivy-match-required-face ((t (:inherit link :underline nil :weight bold))))
 '(lazy-highlight ((t (:background "gray58" :foreground "#c0c0c0"))))
 '(link ((t (:foreground "orchid4" :underline t))))
 '(link-visited ((t (:inherit link :foreground "MediumPurple4"))))
 '(match ((t (:inherit (link highlight) :underline nil :weight bold))))
 '(mode-line ((t (:background "#a0a0a0" :foreground "#595959" :box (:line-width 1 :color "#a0a0a0")))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#a0a0a0" :foreground "#c0c0c0" :box (:line-width 1 :color "#a0a0a0") :weight light))))
 '(org-agenda-done ((t (:foreground "PaleGreen"))))
 '(org-column ((t (:background "grey63" :strike-through nil :underline nil :slant normal :weight normal))))
 '(org-column-title ((t (:background "grey63" :underline t :weight bold))))
 '(org-date ((t (:foreground "gray45" :underline t))))
 '(org-done ((t (:foreground "gray50" :weight bold))))
 '(org-hide ((t (:foreground "#b9b9b9"))))
 '(org-level-1 ((t (:inherit outline-1 :weight bold))))
 '(org-level-2 ((t (:inherit outline-2 :weight bold))))
 '(org-level-3 ((t (:inherit font-lock-type-face :weight bold))))
 '(org-level-4 ((t (:inherit link :underline nil :weight bold))))
 '(org-level-5 ((t (:inherit outline-5 :foreground "SkyBlue4" :weight bold))))
 '(org-level-6 ((t (:inherit outline-6 :weight bold))))
 '(org-level-7 ((t (:inherit outline-7 :weight bold))))
 '(org-level-8 ((t (:inherit outline-8 :weight bold))))
 '(org-mode-line-clock ((t (:inherit mode-line :foreground "gray78"))) t)
 '(org-mode-line-clock-overrun ((t (:inherit mode-line :foreground "gray78" :weight bold))) t)
 '(org-special-keyword ((t (:inherit font-lock-comment-face :foreground "gray50" :slant italic :weight normal))))
 '(org-table ((t (:inherit default))))
 '(org-todo ((t (:foreground "gray40" :weight bold))))
 '(region ((t (:background "grey75"))))
 '(semantic-highlight-func-current-tag-face ((t (:inherit highlight))))
 '(sh-heredoc ((t (:inherit font-lock-string-face))))
 '(sh-quoted-exec ((t (:inherit font-lock-builtin-face))))
 '(show-paren-match ((t (:background "#999999" :foreground "#c0c0c0"))))
 '(show-paren-mismatch ((t (:background "PaleVioletRed4" :foreground "#c0c0c0"))))
 '(speedbar-tag-face ((t (:inherit link :underline nil))))
 '(swiper-line-face ((t (:inherit highlight))))
 '(swiper-match-face-2 ((t (:inherit isearch-lazy-highlight-face))))
 '(swiper-match-face-3 ((t (:inherit isearch-lazy-highlight-faec))))
 '(swiper-match-face-4 ((t (:inherit isearch-lazy-highlight-face))))
 '(vertical-border ((t (:foreground "#a9a9a9")))))
