#! /bin/bash

# ~/Desktop \
# ~/.emacs.d \
# ~/.gitconfig \
# ~/Documents \
# ~/Downloads \
# ~/Library \
# ~/Movies \
# ~/Music \
# ~/Pictures \
# ~/local \
# ~/opt \
# ~/src \

scripts_dir=~/src/scripts
exclude_file="${scripts_dir}/backup-exclude-files"
include_file="${scripts_dir}/backup-include-files"

echo $include_file

if [[ $# -gt 0 ]]; then
    target=$1
else
    echo "Usage: Must specify a target directory"
    exit 1
fi

echo "Backing up files to $target"
eval rsync -avvz --partial --progress --delete --delete-excluded --recursive --exclude-from $exclude_file --files-from $include_file ~/ $target
