#! /bin/bash

for FILE in *.mp3 ; do
    if [[ $(id3v2 -l "$FILE" | grep -c id3v2) -eq 0 ]] ; then
	echo Warning: "$FILE" does not contain id3v2 tags, checking id3v1...
	if [[ $(id3v2 -l "$FILE" | grep -c id3v1) -ne 0 ]] ; then
	    id3v2 -C "$FILE"; # Conert id3v1 tags to id3v2
	    id3v2 -s "$FILE"; # Strip id3v1 tags
	else
	    echo Error, "$FILE" does not contain id3v2 or idv1 tags...
	    exit 0;
	fi
    elif [[ $(id3v2 -l "$FILE" | grep -c id3v1) -ne 0 ]] ; then
	echo id3v2 tags exist, removing id3v1 tags...
	id3v2 -s "$FILE"; # Strip id3v1 tags
    fi
    echo Renaming "$FILE"... 

# Rename file <tracknumber> <title> using only alphanumeric characters, space, ",", ".", and "'". All other characters are replaced with an underscore "_".
    mv "$FILE" "$(printf "%02d" $(id3v2 -l "$FILE" | egrep \(TRCK\|TRK\) | sed 's/TRCK (Track number\/Position in set): *0*//; s/TRK (Track number\/Position in set): *0*//; s/\/[0-9]*$//')) $(id3v2 -l "$FILE" | egrep \(TIT2\|TT2\) | sed "s/TIT2 (Title\/songname\/content description): //; s/TT2 (Title\/songname\/content description): //; s/[^\'\.\, A-Za-z0-9]/_/g").mp3";
done

# Removes non-ascii characters, ex: "%EF"
for FILE in *.mp3 ; do
    mv "$FILE" "$(echo "$FILE" | sed 's/%[A-Za-z0-9]\{2\}/_/g')";
done